name: ci

on: push

jobs:
  dialyzer:
    strategy:
      matrix:
        elixir: ['1.8', '1.9', '1.10']

        otp: ['22.2']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1

        with:
          key: dialyzer-${{ matrix.elixir }}-otp-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}

          path: _build

      - uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}

          otp-version: ${{ matrix.otp }}

      - name: Run mix deps.get

        run: mix deps.get

      - name: Run mix compile

        run: mix compile

      - name: Run mix dialyzer

        run: mix dialyzer

  test:
    strategy:
      matrix:
        elixir: ['1.8', '1.9', '1.10']

        otp: ['22.2']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1

        with:
          key: test-${{ matrix.elixir }}-otp-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}

          path: _build

      - uses: actions/setup-elixir@v1

        with:
          elixir-version: ${{ matrix.elixir }}

          otp-version: ${{ matrix.otp }}

      - name: Run mix deps.get

        run: mix deps.get

      - name: Run mix compile

        run: MIX_ENV=test mix compile

      - name: Run mix test

        run: mix test
